# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bike_rental.Base')),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rent',
            },
            bases=('bike_rental.base',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bike_rental.Base')),
                ('name', models.CharField(max_length=20, null=True)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('bike_available_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'station',
            },
            bases=('bike_rental.base',),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('latitude', 'longitude')]),
        ),
        migrations.AddField(
            model_name='rent',
            name='destination_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='destination_for_rents', to='bike_rental.Station'),
        ),
        migrations.AddField(
            model_name='rent',
            name='origin_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='origin_for_rents', to='bike_rental.Station'),
        ),
    ]
