# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0001_added station and rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='destination_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_for_rents', to='bike_rental.Station'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='origin_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_for_rents', to='bike_rental.Station'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
